spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:your-news}?rewriteBatchedStatements=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASS:password}

--- # rabbitMQ
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:root}
    password: ${RABBITMQ_PASSWORD:}

rabbitmq:
  queue-name: ${RABBITMQ_QUEUE_NAME:queue}
  exchange-name: ${RABBITMQ_EXCHANGE_NAME:exchange}
  routing-key: ${RABBITMQ_ROUTING_KEY:key}

--- # firebase
firebase:
  key: ${FIREBASE_KEY}