name: Deploy - notify

on:
  push:
    branches: ["main"]

jobs:
  deploy-notify:
    runs-on: ubuntu-latest

    steps:
      # 1. push된 커밋 기준 코드 내려 받기
      - name: Checkout PR
        uses: actions/checkout@v3

      # 2. 자바 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Firebase를 위한 JSON 파일 생성
      - name: Create Json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "./src/main/resources/your-news-735fe-firebase-adminsdk-fbsvc-bfc443350c.json"
          json: ${{ secrets.FIREBASE_PRODUCTION_JSON }}

      # 4. Build Gradle
      - name: Build notify
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      # 5. 현재 커밋의 짧은 SHA 값을 가져와 VERSION 환경변수로 등록
      - name: Set VERSION from short SHA
        id: version
        run: |
          echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # 6. Docker 이미지 build 및 push
      - name: Docker Build & Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/yournews-notify:$VERSION .
          docker tag ${{ secrets.DOCKER_USERNAME }}/yournews-notify:$VERSION ${{ secrets.DOCKER_USERNAME }}/yournews-notify:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/yournews-notify:$VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/yournews-notify:latest

      # 7. AWS 자격 증명 구성
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 8. AWS CLI 설치
      - name: Install AWS CLI
        run: |
          curl -sS https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      # 9. SSM Run Command로 EC2 배포 스크립트 실행
      - name: Deploy with SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy yournews-notify via GitHub Actions" \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --region ap-northeast-2 \
            --parameters commands='bash /home/ssm-user/script/deploy.sh' \
            --output text
